DROP DATABASE HOSPTIAL;
CREATE DATABASE HOSPTIAL;
USE HOSPTIAL;
DROP TABLE IF EXISTS RECEPTIONIST;
CREATE TABLE RECEPTIONIST 
(
R_NAME VARCHAR(10) NOT NULL,
R_ID INT PRIMARY KEY,
R_GENDER CHAR,
R_DESIGINATION VARCHAR(100),
R_DATE_OF_BIRTH DATE,
R_AGE INT,
R_SHIFT_TIME TIMESTAMP,
R_CONTACT_NUMBER VARCHAR(10),
R_ADDRESS VARCHAR(10),
check(R_ID<=2)
);
SELECT * FROM RECEPTIONIST;
ALTER TABLE RECEPTIONIST MODIFY COLUMN R_SHIFT_TIME TIMESTAMP;